#pragma once

enum COMMUNICATOR_CMD
{
	CMD_NULL = 0,
	CMD_RESPONSE_COMMUNICATION_STATE,		//下位机返回连接状态
	CMD_RESPONSE_FAULT,						//下位机返回错误代码
	CMD_RESPONSE_WARN,

	CMD_RESPONSE_ACQUIREMODE,				//下位机返回采集模式
	CMD_RESPONSE_EPID_OPENCTRL_ACK,
	CMD_RESPONSE_EPID_CLOSECTRL_ACK,
	CMD_RESPONSE_EPID_MOVESTATE,
	CMD_RESPONSE_BED_XCTRL_ACK,
	CMD_RESPONSE_BED_XCTRL_MOVETO_ACK,
	CMD_RESPONSE_BED_YCTRL_ACK,
	CMD_RESPONSE_BED_YCTRL_MOVETO_ACK,
	CMD_RESPONSE_BED_ZCTRL_ACK,
	CMD_RESPONSE_BED_ZCTRL_MOVETO_ACK,
	CMD_RESPONSE_BED_MOVESTATE,

};


enum CONNECT_STATE
{
	UNKNOW = 0,
	CONNECT_INIT_FAILED,		//串口初始化失败
	CONNECT_SUCCESS,			//下位机连接成功
	CONNECT_FAILED,				//下位机连接失败
};

enum ACQUIREMODE
{
	ACQUIREMODE_TREATMENT = 0,			//治疗模式
	ACQUIREMODE_QA						//QA模式

};

enum EPID_STATE
{
	EPID_STATE_ERROR = 0,
	EPID_STATE_OPEN,
	EPID_STATE_CLOSE,
	EPID_STATE_OPEN_ING,
	EPID_STATE_CLOSE_ING,
};

enum EPID_MOVESTATE//retiring
{
	EPID_MOVESTATE_ABNORMALSTOP = 0,
	EPID_MOVESTATE_OPEN_OVER,
	EPID_MOVESTATE_CLOSE_OVER,
	EPID_MOVESTATE_MOVING,
};

enum MOVECTRL
{
	MOVECTRL_STOP = 0,		//停止
	MOVECTRL_POSITIVE,		//正向运动
	MOVECTRL_NEGATIVE,		//反向运动
};

enum TREATMENTBED_MOVESTATE
{
	TREATMENTBED_MOVESTATE_UNFINISHED = 0,
	TREATMENTBED_MOVESTATE_FINISHED,
};




